name: Deploy to WordPress.org
on:
  workflow_dispatch:
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: WordPress Plugin Deploy
      uses: varunsridharan/action-wp-org-deploy@master
      with:
        WORDPRESS_PASSWORD: V)U4p6ViPRG4HXW
        WORDPRESS_USERNAME: xirosoft
        SLUG: themes-assistant
      env:
        GITHUB_TOKEN: ${{ secrets.ADVANCE_THEMES_ASSISTANT }}
